### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#10]
As a registered zero shop owner, I can add the data of my shop so that website users can find my shop

**Acceptance Criteria**
- [ ] 'Add' button launches Form for registered shop owner to add store data
- [ ] Submit button on form submits form

**Tasks**
- [ ] 1) Store Shop Owner in DB so they can login with their credentials 
- [ ] 2) Include 'Add Shop' link on Home Page 
- [ ] 3) Create Model for Shop 
- [ ] 4) Connect form on Add Shop template page to Shop model
- [ ] 5) Add Style to Default Login
