### ISSUE TITLE
Add New Shop

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#11]
As a registered zero shop owner, I can add the data of my shop so that website users can find my shop

**Acceptance Criteria**
- [ ] 'Add' button launches Form for registered shop owner to add store data
- [ ] Submit button on form submits form

**Tasks**
- [ ] 1) Logged in Store owner can see 'Add Shop' link on their Home Page view
- [ ] 2) Include 'Add Shop' link on Home Page 
- [ ] 3) Create Model for Shop 
- [ ] 4) Connect form on Add Shop template page to Shop model

**Comment by MoniMurray** [comment]
Register instead of Add being used on Home page.
