### ISSUE TITLE
Location and Category search function

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#12]
As a website user, I can select a Location and a Category so that I can see the zero waste shops in my area

**Acceptance Criteria**
- [ ] 1) dropdown buttons on Location and Category launch data within
- [ ] 2) Search button launches search on database
- [ ] 3) Available data returned to user via a Card for each shop 

**Tasks**
- [ ] 1) Create dropdown buttons on Location and Category to be populated from Shop model data
- [ ] 2) Add Search button to launch search on database
- [ ] 3) Create Cards for each shop
