### ISSUE TITLE
Update or Delete Shop

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#13]
As a zero waste shop owner, I can update and delete details about the shop that I registered  so that I can keep the data updated

**Acceptance Criteria**
- [ ] 1) Logged in Shop Owner can see an edit and delete feature on their Shop data fields
- [ ] 2) Data fields are editable
- [ ] 3) Shop can be deleted using Delete Button
- [ ] 4) Click 'Submit' edits Shop data in database

**Tasks**
- [ ] 1) Create Forms for updating and deleting user details 
- [ ] 2) Create Template for registered shop owner to modify/delete their details
- [ ] 3) Create View for the template
- [ ] 4) Add Styling to Template
