### ISSUE TITLE
Interactive Map with directions to shop

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#14]
As a website user, I can click on the shop pin on the Map and will be directed to Google Maps with the Shop Location route so that i can easily find the shortest way to the shop from where I am

**Acceptance Criteria**
- [ ] 1) Maps works as intended
- [ ] 2) Google Maps open in a new page with direction to shop

**Tasks**
- [ ] 1) Add Div to Home page containing a google map 
- [ ] 2) Add pins to the map with the selected shops
- [ ] 3) when the user click on a pin, they see information about the shop
- [ ] 4) Add option to link the pin with google maps navigation
- [ ] 5) Add dialog confirming that his action would leave the page

**Comment by MoniMurray** [comment]
Due to time constraints, this will be a future feature. An embedded map has been implemented for this iteration.
