### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#18]
As a website user, I can view the footer from every page so that I can access it's contents

**Acceptance Criteria**
- [ ] footer views across all pages

**Tasks**
- [ ] 1) build a footer template
- [ ] 2) make the footer template available across every page through inclusion in the base template
