### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#19]
As a website user, I can see colourful favicon on the browser to help understand the site's purpose

**Acceptance Criteria**
- [ ] 1) View a favicon on the browser beside the website name 

**Tasks**
- [ ] 1) Choose an image to use as a favicon
- [ ] 2) Go to favicon.io website, drag in image and download zip file containing png files of differing sized images
- [ ] 3) Import links to base.html
