### ISSUE TITLE
Carbon Calculator

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#20]
As a website user, I can calculate the amount of carbon when I use a carbon calculator that I can find on the page so that I can make informed choices when purchasing and consuming products

**Acceptance Criteria**
- [ ] Calculator page launches from Navigation bar on all pages
- [ ] Form fields accept data
- [ ] Calculator works on 'Calculate' button

**Tasks**
- [ ] 1) Create the Calculator app
- [ ] 2) Create the MVT for the calculator, to open on a new template page launched from Navigation bar
- [ ] 3) Design a form for the template where user fills in details about their consumption behaviour (i.e. 2 PET bottles/day)
- [ ] 4) Create html for the page  
- [ ] 5) Add javascript script to calculate the estimated waste  based on the form, and display the result to the user
- [ ] 6) Add style to the page
- [ ] 7) Link the page to the navbar of the base template

**Comment by ObiOne84** [comment]
I will need to update the product names and emission rates. I will try to remove emission rates from the HTML and create an object for them to declutter the view. I will change the side total to whatever frequency is chosen so that only the bottom count will show the yearly emission.
