### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#7]
As a User I can view the Home Page of the website so that I can see what the site is for

**Acceptance Criteria**
- [ ] The Page is responsive
- [ ] The code follow semantic standards

**Tasks**
- [ ] 1) Create a base template called 'base.html' in the root
- [ ] 2) Add styling to template
- [ ] 3) Create an index.html to extend base template in the 'home' app
- [ ] 4) Use Tailwind framework to develop fully responsive and accessible home page
