### ISSUE TITLE
Site Navigation bar

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#8]
As a website user, I can view the navbar from every page so that I can navigate around the website

**Acceptance Criteria**
- [ ] view and navigation the features of the navigation bar across all website pages

**Tasks**
- [ ] 1) build a navigation view template
- [ ] 2 make the navigation template available across every page through inclusion in the base template
