### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/september_hackathon_team7_wastewizeweb#9]
As a zero shop owner, I can register with the data of my shop so that website users can find my shop

**Acceptance Criteria**
- [ ] 1) Registration link in home page launches registration screen
- [ ] 2) required fields in login page prompt for data
- [ ] 3) submit button works

**Tasks**
- [ ] 1) install Django AllAuth
- [ ] 2) Create Model for Shop Owner 
- [ ] 3) Store Shop Owner in DB so they can login with their credentials
- [ ] 4) Add Style to Default Signup Template
- [ ] 5) Add link from navigation to launch Signup Template
